### ISSUE TITLE
Several seconds delay when saving a datacartridge

### ISSUE THREAD

**Issue by tumbler31** [tumbler31/BMS-test#10]
**Describe the bug**
Saving a DTC takes 4-6seconds. Note, also loading a TE takes significantly longer than in 4.37.5

**To Reproduce**
1. load a TE, eg TE_BMS_10 multination war
2. open dtc
3. click save

**Expected behavior**
Almost instantly see 'saved OK' when pressing 'save'

**Comment by tumbler31** [comment]
I did some testing and it doesn’t make any sense. If I run the release config in the IDE it’s fast, if I copy the built exe to the test folder it’s slow. Same cfg, same TE, same (empty) ini’s, both with -mono output.

I added some logging and the slow commands are the various `WritePrivateProfileSectionA()` calls.

**Comment by tumbler31** [comment]
Windows Defender is causing the slow down, when disabling Windows Defender performance is back. Seems BMS signature has changed into something suspicious according to Windows Defender :(

**Comment by BertNienhuis** [comment]
For future reference; follow these steps to exclude the BMS folder from your Windows Defender: 
https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26#:~:text=Go%20to%20Start%20%3E%20Settings%20%3E%20Update,%2C%20file%20types%2C%20or%20process.
