### ISSUE TITLE
F-15C - VSD Side bump goes to 20deg AZ Scan instead of 60deg AZ Scan

### ISSUE THREAD

**Issue by Saint-BMS** [tumbler31/BMS-test#11]
**Describe the bug**
When in 120deg AZ (Any Bar) Search, bumping side of VSD reduces AZ scan volume to 20deg instead of the intended 60deg

**To Reproduce**
Any flight in F-15C, bump side of VSD, AZ scan goes to 20deg

**Expected behavior**
AZ scan should be 60deg

**Screenshots**
N/A

**Comment by tbuckup** [comment]
not straight forward in the current change mode routine , so will be done in 38
