### ISSUE TITLE
F-15C Auto-Acq switch DOWN does not work with slipway open

### ISSUE THREAD

**Issue by Saint-BMS** [tumbler31/BMS-test#4]
**Describe the bug**
F-15C Auto-Acq switch DOWN does not work with slipway open

**To Reproduce**
1. F-15C Navigation Training
2. Locked contact in STT, opened slipway, attempted to REJECT lock by Auto-Acq switch DOWN (depressed), it would not drop lock. Closed slipway and now works as intended

**Expected behavior**
Expected behavior is no change to Auto-Acq switch functionality with slipway open

**Screenshots**
N/A

**Comment by tbuckup** [comment]
will check

**Comment by tbuckup** [comment]
fixed, please check next internal

**Comment by Saint-BMS** [comment]
> @Saint-BMS can we consider this one fixed and can I close it?

It appears fixed.
