### ISSUE TITLE
4.37.6.2, build 2966 FOV with the mouse wheel is too slow

### ISSUE THREAD

**Issue by VIPER-0-BT** [tumbler31/BMS-test#7]
FOV with the mouse wheel is too slow, it takes about 5 turns to zoom from the default FOV of 60 to the closest possible, the same with the keyboard inputs you have to make too many hits in the keys to get to the closest FOV

I found this line in falcon bms.cfg

**set g_fFOVIncrement 5 // Sets how much the field of view should change for each keypress in degrees**

but I had never had to touch or increase this value to have a quick reaction when making the FOV closer
now I had to increase the value from 5 to 20, to have the same reaction as before.

**_PS: In 4.37.5 it behaves the same as always, correctly, with the same reaction speed and the same amount of mouse wheel movement as all previous versions U3, U4_**

**Comment by arithex** [comment]
Confirmed repro .. thanks!

**Comment by tumbler31** [comment]
fix confirmed
