### ISSUE TITLE
4.37.6.2 Screen sizes/positions still not being saved between sessions

### ISSUE THREAD

**Issue by MalcBMS** [tumbler31/BMS-test#8]
As per title, if I am in 3D then return to UI, next 3D sessions reverts to 1920x1080 instead of set 3440x1440

**Expected behavior**
Screen resolutions to be saved between sessions

**Comment by tumbler31** [comment]
Does this happen in 4.37.5 as well?

**Comment by MalcBMS** [comment]
Setup in 4.375 was 
2D 1920x1080, 3D 3440x1080 - never had any issues personally.

4.37.6.1 and 4.37.6.2, same settings, initial 2D fine, initial 3D fine, back to 2D fine, recommit to 3D has resized to 1920x1080.

Go back to 2D, reset to 3440x1440, commit to 3D fine.

Close BMS completely, cycle starts again. First commit to 3D is fine, after which it resets to 1920x1080. Hope this makes sense.

Side question… as with devicesorting.txt, if I were to make the .dsp read only would this be okay?

**Comment by MalcBMS** [comment]
set g_fCursorSpeed 1.25
set g_bMFDHighContrast 1
set g_bBarcapNoBarcap 1
set g_fDefaultFOV 80
set g_bPlayIntroMovie 0
set g_bRampTaxiStart 1
set g_bHotasDgftSelfCancel 1

set g_sLogsDirectory "E:\_BMS\Logs"                              // If set, redirects the logfile output from <BMS>\User\Logs to the specified directory.
set g_sAcmiDirectory "E:\_BMS\Acmi"                              // If set, redirects the ACMI directory from <BMS>\User\Acmi to the specified directory.
set g_sPicturesDirectory "E:\_BMS\Pictures"                      // If set, redirects the pictures directory from <BMS>\User\Pictures to the specified directory.
set g_sBriefingsDirectory "E:\_BMS\Briefings"                    // If set, redirects the briefing output from <BMS>\User\Briefings to the specified directory.
set g_sPatchesDirectory "E:\_BMS\Patches"                        // If set, redirects the patches directory from <BMS>\User\Patches to the specified directory.

set g_bPlayDogfightBits 0
set g_nScaleUIMode 0
set g_bExportRTTTextures 1
set g_fAmbientmin 0.03
set g_nVRHMD 1  
set g_nAxisExp_AXIS_YAW 30
set g_nAxisSat_AXIS_YAW 8

set g_fMaximumFOV 120                                 // Limits the maximum amount that the FOV can be increased.

set g_bDetailedFrameRate 0
set g_bWindowedRadioSubtitles 0                      //
set g_nCloudRotationMethod 1                         // “face camera position” (as opp. to"camera direction")
set g_bAfterburnerDetentClick 1                      // Makes the same clicks when the throttle passes the afterburner detent as it does when passing the Idle detent.
set g_bLogInputFunctions 1

set g_sPPTRingColor "0xF0F0F0"                       // The color of the UI map PPT rings, set as hex, "0xBBGGRR".
set g_nPPTRingWidth 2

set g_nVRHMD 1                                       // Enables the OpenVR (default 0/false).
set g_bMixedRealityCockpitCoverEnabled 0             // Setting this will default the Mixed Reality Cockpit Cover on (1) or off (0). Can still be toggled in game.

**Comment by arithex** [comment]
I think this is a known-issue, if visiting the Setup screen at all in 2d..   it will overwrite d3d11.dsp with what it thinks you want from the dropdown.

I will try to fix this to be smarter.

**Comment by arithex** [comment]
@MalcBMS  Giving this further attention -- I'm not able to repro.   If you give me more detail I'll try again...

1- your config says VR (`set g_nVRHMD 1`) but I assume this question is about pancake - not the VR companion window?

2- how many monitors .. what are their dimensions (resolutions)

3- is your intent to fly in Fullscreen or Borderless mode?

3b - what adapter/output and resolution are selected, in the Setup/Graphics screen (make sure it reflects your desired adapter and monitor resolution - 3440x1440? - even if flying Borderless mode)

4- you mention 2d is 1920x1080 .. but the current expected behavior is 2d UI will fill the primary Windows desktop monitor (assuming bordered or borderless window mode)  .. is your primary monitor 1920x1080?   (if so, that's fine -- if not, what did you mean exactly)

If you specify g_fScaleUIFactor less than 1.0, it will downsize the 2d UI accordingly (eg. `set g_fScaleUIFactor 0.75` will give you a 1920x1080 window, if your primary Windows desktop is 2560x1440) but I didn't see that in the cfg

**Comment by MalcBMS** [comment]
Hi mate,

1. Yes, pancake mode. I am mostly using VR now but for multiplayer I am still pancake for ease of access to extra hardware attached to the second screen (UFC ICP and TM MFDs).

2. I have three monitors - primary is 34” 3440x1440, second is 22” 1920x1080, third is 43” 3840x1440. I use the primary for UI and 3D, the second monitor is for RTT extraction, etc. Third one is only for sim-racing.

3. When pancake, I have the UI set to 1920x1080 windowed borderless and roughly centred on the screen, and 3D is 3440x1440 windows borderless.

4. I don’t use a maximised or full screen UI cos I like to have access to web browser, etc while in the UI for ease of access to Discord, etc. No downscaling of the UI specified/required.

Hope this helps?

**Comment by MalcBMS** [comment]
Sorry, forgot to add - 4080 Super, displays 1 and 3 are HDMI, display 2 is DP, all are set no native resolutions.

**Comment by arithex** [comment]
>     3. When pancake, I have the UI set to 1920x1080 windowed borderless and roughly centred on the screen, 

How are you achieving this - please clarify.  (I don't see g_fScaleUIFactor anywhere in your cfg.)

**Comment by arithex** [comment]
Also please answer (3b) .. what monitor Output and Resolution does the Setup/Graphics page show, selected in the dropdown.

**Comment by MalcBMS** [comment]
It is easier to show you than try to explain :)

Hopefully this will be enough to answer your questions - https://youtu.be/StvD70UhBSk

**Comment by arithex** [comment]
Thanks -- ok I did all those things, with `set g_fScaleUIFactor 0.75` .. entered dogfight/furball and back .. no repro.

My primary monitor is 4k (3840x2160) so that's a little different, but it was the same, before and after entering 3d.

Not sure how to proceed..  can you zip up your Config folder and share it to me.   Do it after exiting 3d, confirm that it's in the broken state in Setup/Graphics screen, and click apply then ok, so it saves to d3d11.dsp

**Comment by MalcBMS** [comment]
Changing set g_nScaleUIMode 0 to 1 and adding set g_fScaleUIFactor 0.75 doesn't stop the reverting after exiting 3D

**Comment by arithex** [comment]
oh I see `set g_nScaleUIMode 0` is how you got 1920x1080 window for 2d UI ..  sorry I didn't see that at first

but I tried that, and still no repro on my end .. something else is going wrong.

can you share the xlog file from a session where you do the steps on your youtube video

**Comment by MalcBMS** [comment]
XLog from recorded session as requested = https://www.mediafire.com/file_premium/6oyxff57va44lu0/Malc-BrokenState-xlog.zip/file

**Comment by arithex** [comment]
thanks - sadly nothing jumps out at me as wrong, there..  it consistently says
```
SaveValues storing sim mode: width 3440, height 1440, refreshRate (59973/1000), scaling 0, scanlineOrdering 1, surfaceFormat 87
```

**Comment by MalcBMS** [comment]
Is it possible the file is being rewritten again after leaving 3D and returning to the UI, hence saving the UI dimensions rather than the 3D?

**Comment by arithex** [comment]
Currently, the situation is this -- if you go into Setup/Graphics (actually any Setup screen, I think) and click 'apply' or 'ok' it will overwrite the d3d11.dsp with a desired width/height based on whatever is selected in that 'Resolution' dropdown

That's a little unexpected and I need to make it smarter .. but it's not a problem, in practice, for most -- on my test systems, the value there remains unchanged

One possible culprit for this bug, is the DirectX call to FindClosestMatchingMode which may be misbehaving, for reasons I don't understand, but I have heard others reporting similar issues
 https://learn.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgioutput-findclosestmatchingmode

But if it's that, I would expect it to pick a mode closer to 3440x1440 .. eg. maybe 2560x1440 .. that's what others have observed.

I'll take a closer look at the log output..

**Comment by arithex** [comment]
hmm wait, I think I see the problem..  wtf this shouldn't be here

```
[03:00:10.478] 11964 VR: center left: [0.000000, 0.000000]
[03:00:10.478] 11964 VR: center right: [0.000000, 0.000000]
[03:00:10.478] 11964 [OpenXR Exception]: XrResult = -10, Origin: xrCreateInstance(&createInfo, &m_instance)
[03:00:10.478] 11964 XrResult = -10, Origin: xrCreateInstance(&createInfo, &m_instance)[03:00:10.478] 11964 Starting TimerLoop Thread 0x0000000004B5C7F0 
```

**Comment by arithex** [comment]
I can reproduce the problem now..  This is happening when I do `set g_nVRHMD 1` in my user cfg, but I don't actually have SteamVR runtime installed or enabled, and when I don't specify -novr on the command line, to override the cfg.

Which VR platforms do you have installed?  And how, precisely, are you launching BMS.

There are some weird codepaths that we're falling down through.. when the cfg doesn't match what's installed and available.

**Comment by MalcBMS** [comment]
Great that you’ve made progress!

I start the sim using the original launcher, which I start via my own creation I call multi launcher. This simple program lets me specify my “add-ons” - RTT, MFDE, OBS, etc. It also has an checkbox which lets me specify if I want to use VR or not which adds the -xr parameter to the command line. I can send you this if you like? I have been using this for a good while now, and it’s only since 4.37.6.1 have I started to have this issue. I have never used the new Alternative Launcher.

I have SteamVR installed for when I play ACC. I did have the OpenXR Toolkit installed, but have since uninstalled that following recent advice here.

**Comment by arithex** [comment]
As a quick check, can you remove g_nVRHMD from your cfg .. or rather, set it 0 in BMS cfg and remove it from User cfg

Then launch `Falcon BMS.exe -novr` directly 

See if the problem still repros

**Comment by MalcBMS** [comment]
Hi mate, enter/exit 3D five times in a row and no problems, output remained at 3440x1440 as desired. Good job.

**Comment by arithex** [comment]
Cool, good to know that workaround exists .. I'll see if I can harden this error-path, for U6

**Comment by MalcBMS** [comment]
Good job, in 6.3 I cannot break this - test with -xr switch and without -xr switch. safe to call it Fixed I believe.
